---
swagger: "2.0"
info:
  description: "Basic project with Flask and Connexion"
  version: "1.0.0"
  title: "Connexion example"
  contact:
    name: "Pim Witlox"
basePath: "/api/v1"
tags:
  - name: "alive"
    description: "Keepalive"
produces:
  - "application/json"
consumes:
  - "application/json"
paths:
  /ping:
    get:
      tags:
        - "alive"
      summary: "Api keepalive"
      description: "Api keepalive"
      operationId: "is_alive"
      parameters: []
      responses:
        200:
          description: "is alive"
      x-swagger-router-controller: "horao.controllers.alive_controller"
