name: coverage

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  build:
    name: poetry run code coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        poetry-version: ["1.8.4"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==${{ matrix.poetry-version }}
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path .virtualenvs
      - name: Install project
        run: poetry install --with test --no-interaction
      - name: Test with poetry
        run: poetry run pytest
      - name: Assert coverage of package is above 80%
        uses: zlatko-ms/pycovcheck@v2
        with:
          coveragefile: ./coverage.xml
          packages: |
            horoa.api:0.50
            horoa.auth:0.60
            horoa.conceptual:0.60
            horao.controllers:0.80
            horao.logical:0.60
            horao.persistence:0.1
            horao.physical:0.60
            horao.rbac:0.50

