name: poetry

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  build:
    name: poetry build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies using poetry
        run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - name: Install project
        run: poetry install --no-interaction
      - name: Test with poetry
        run: poetry run pytest
